### ISSUE TITLE
[Docs] Build is broken

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#523]
It looks like the Docs build is broken since we introduced the header. cc @JonasBa 

I simply ran `make`.

```
node index.js
/Users/raymond/Code/vvv/www/wordpress-default/public_html/wp-content/plugins/algoliasearch-wordpress/docs/node_modules/algolia-components/components/communityHeader/communityHeader.html.js:61
       data-dropdown="${ view.toLowerCase() }" data-enabledropdown="${ dropdownItems.length > 0 }">
                             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at renderMenu (/Users/raymond/Code/vvv/www/wordpress-default/public_html/wp-content/plugins/algoliasearch-wordpress/docs/node_modules/algolia-components/components/communityHeader/communityHeader.html.js:61:30)
    at renderMenuList (/Users/raymond/Code/vvv/www/wordpress-default/public_html/wp-content/plugins/algoliasearch-wordpress/docs/node_modules/algolia-components/components/communityHeader/communityHeader.html.js:72:17)
    at Object.module.exports [as communityHeader] (/Users/raymond/Code/vvv/www/wordpress-default/public_html/wp-content/plugins/algoliasearch-wordpress/docs/node_modules/algolia-components/components/communityHeader/communityHeader.html.js:199:15)
    at Object.<anonymous> (/Users/raymond/Code/vvv/www/wordpress-default/public_html/wp-content/plugins/algoliasearch-wordpress/docs/index.js:34:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
make: *** [build] Error 1
```

**Comment by JonasBa** [comment]
@rayrutjes Can you pull the `add-remove-logo-instructions` and make sure to remove `node_modules` and `yarn.lock` as I have updated the dependency to a npm package. After that just yarn install and try to run make build?

**Comment by rayrutjes** [comment]
It works now @JonasBa , thanks! 

Could we make the links relative so that when I click on `documentation` in dev mode I access the page instead of a 404?

If it is too complex, not a big deal.
